/*155P, 0으로 잘라내는 함수.*/
SELECT TRUNC(1234.5678) AS TRUNC,
TRUNC(1234.5678, 0) AS T_O,
TRUNC(1234.5678, 1) AS T_1,
TRUNC(1234.5678, 2) AS T_2,
TRUNC(1234.5678, -1) AS T_M1,
TRUNC(1234.5678, -2) AS T_M2
FROM DUAL;

/* 156P */
SELECT ROUND(1234.5678) AS R,
ROUND(1234.5678, 0) AS R0,
ROUND(1234.5678, 1) AS R1,
ROUND(1234.5678, 2) AS R2,
ROUND(1234.5678, -1) AS RM1,
ROUND(1234.5678, -2) AS RM2
FROM DUAL;

SELECT CEIL(3.14) AS CEIL,
FLOOR(3.14) AS FLOOR,
CEIL(-3.14) AS CEIL_M,
FLOOR(-3.14) AS FLOOR_M
FROM DUAL;

--파워 : 숫자, 제곱승
SELECT POWER(3, 2),
POWER(-3, 3)
FROM DUAL;

--절대값 반환
SELECT ABS(-100), ABS(100), ABS(0)
FROM DUAL;

--날짜 SYSDATE
SELECT SYSDATE  AS NOW
	, SYSDATE-1 AS YESTERDAY
	, SYSDATE+1 AS TENDAYS
FROM DUAL;
-- 현재날짜 + 0개월 뒤
SELECT SYSDATE , ADD_MONTHS(SYSDATE, 5)
FROM DUAL;
--입사일로부터 20년 뒤(ADD_MONTHS 밖에 없어서 곱해주기)
SELECT EMPNO, ENAME, HIREDATE,
ADD_MONTHS(HIREDATE, 12*20) AS WORK_10YEARS
FROM EMP;
--오늘 날짜 기준으로 입사한지 40년 이상 된 직원은?
SELECT EMPNO, ENAME, HIREDATE, SYSDATE 
FROM EMP
WHERE ADD_MONTHS(HIREDATE, 12*40) > SYSDATE ;
--입력한 날찌 사이의 개월 수 계산해보기
SELECT ENAME, HIREDATE, SYSDATE 
	, MONTHS_BETWEEN(HIREDATE, SYSDATE)/12 AS YEAR1
	, MONTHS_BETWEEN(SYSDATE, HIREDATE)/12 AS YEAR2
	, TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)/12) AS YEAR3
	FROM EMP;
	
--SYS 날짜를 연,월,일 문자형식으로 반환하기(TO_CHAR는 문자열반환)
SELECT EMPNO,
	EXTRACT (YEAR FROM HIREDATE) AS YYYY
	, EXTRACT (MONTH FROM HIREDATE) AS MM
	, EXTRACT (DAY FROM HIREDATE) AS DD
	FROM EMP;
--연습
SELECT DEPTNO
FROM EMP
WHERE DEPTNO = '20'; --문자 20으로 검색했으나, NUMBER로 자동 형변환.

--SYS날짜를 CHAR 문자형으로 변환하는 작업.
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24') AS DATETIME
FROM DUAL;
--날짜를 분할 추출하기
SELECT SYSDATE 
	, TO_CHAR(SYSDATE, 'MM') AS MM
	, TO_CHAR(SYSDATE, 'MON') AS MON
	, TO_CHAR(SYSDATE, 'MONTH') AS MONTH
	, TO_CHAR(SYSDATE, 'DD') AS DD
	, TO_CHAR(SYSDATE, 'DY') AS DY
	, TO_CHAR(SYSDATE, 'DAY') AS DAY
FROM DUAL;
--국가별 날짜추출 연습(사용거의안함)
SELECT SYSDATE
	, TO_CHAR(SYSDATE, 'MM') AS MM
	, TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = KOREAN') AS MON_KOR
	FROM DUAL;

--문자열로 입력된 00/00/00 날짜를 DATE로 형변환한 뒤 비교하기
SELECT *
FROM EMP 
WHERE HIREDATE > TO_DATE('1981/07/01', 'YYYY/MM/DD');

--YY와 RR의 차이 알기(안씀)
SELECT TO_DATE('49/12/10','YY/MM/DD') AS DATE49
	, TO_DATE('49/12/10','RR/MM/DD') AS DATE49
	, TO_DATE('50/12/10','YY/MM/DD') AS DATE50
	, TO_DATE('50/12/10','RR/MM/DD') AS DATE50
	FROM DUAL;

--최대 자릿수 지정해주기
SELECT TO_NUMBER('3,000','9,999') - TO_NUMBER('1,000','999,999')

--매우중요 NULL처리
--비교할 때 : ISNULL, IS NOT NULL
--NVL(입력값, 대체값) : 널이면 대체값 나와, 널 아니면 입력값 반환돼
SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM
	, NVL(COMM, 0)
	, SAL+NVL(COMM, 0)
	FROM EMP;

--조건에 따라 다른 결과를 반환하는 방법
--DE코드 장점 : 직관적(많이사용)
-- 단점 : 모든 케이스를 다 지정해줘야함
SELECT EMPNO, ENAME, JOB, SAL
	, DECODE(JOB,
		'MANAGER', SAL*0.2,
		'SALESMAN', SAL *0.3,
		'ANALYST', SAL*0.05,
		SAL*0.1) AS BONUS
FROM EMP;

--장점 : 조건을 줄 수 있다
SELECT EMPNO, ENAME, JOB, SAL
	, CASE JOB
	WHEN 'MANAGER' THEN SAL*0.2
	WHEN 'SALESMAN' THEN SAL*0.3
	WHEN 'ANALYST' THEN SAL*0.05
	ELSE SAL *0.1
	END AS BONUS
	FROM EMP;ㅎ